In [ ]:
from platform import python_version
print(python_version())

3.6.9


In [ ]:
import tensorflow as tf
print(f'Tensorflow version currently used is {tf.__version__}')

Tensorflow version currently used is 2.4.0


In [ ]:
import keras
print(f'Keras version currently used is {keras.__version__}')

Keras version currently used is 2.4.3


In [ ]:
import keras
import numpy as np
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [ ]:
#Defining Network with Embedding Layer
embedding_model = keras.Sequential()
embedding_model.add(keras.layers.Embedding(40, 5, input_length=10))

In [ ]:
print(embedding_model.get_weights())

[array([[-3.67733352e-02,  2.13816799e-02,  3.11691277e-02,
        -1.84855089e-02,  3.12627293e-02],
       [-2.72784363e-02, -3.20356861e-02, -4.27203067e-02,
         2.21837796e-02, -2.21992619e-02],
       [-2.57313382e-02, -2.83153057e-02, -1.18870139e-02,
        -2.27215644e-02, -2.59506591e-02],
       [ 2.96994708e-02, -3.32261249e-03, -1.01946965e-02,
        -2.53016707e-02, -4.66327071e-02],
       [-1.36526674e-03,  1.92498453e-02,  9.92731005e-03,
         1.13335624e-02,  3.67391594e-02],
       [-4.25511263e-02, -2.19120625e-02,  1.37923397e-02,
         1.39534473e-03,  3.32311429e-02],
       [ 3.72686870e-02, -3.35258245e-03, -4.98907231e-02,
         1.06737018e-02, -4.59484011e-03],
       [-8.62229988e-03,  3.84036638e-02,  1.95515156e-03,
        -5.55690378e-03,  4.65606526e-03],
       [ 3.89751829e-02, -2.41275914e-02, -2.44956091e-03,
         3.17483209e-02, -4.63805571e-02],
       [-3.65063064e-02, -1.69948451e-02, -4.81019989e-02,
        -6.64304942e-0

In [ ]:
print(embedding_model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 10, 5)             200       
Total params: 200
Trainable params: 200
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
#Define input Samples for Embedding Layer
samples = ['The cat sat on the mat.',
           'The dog ate my homework.',
           'My friend name is Tony Singh',
           'I had visited Dubai last year.',
           'I will visit Singapore next year',
           'I am a Software Engineer ',
           'I got good appraisal this year.',
           'I will change Job next year']

In [ ]:
#creates a tokenizer, configured to only take into account the n most common words
tk = Tokenizer(num_words=40, oov_token='OOV')

In [ ]:
#Builds the word index
tk.fit_on_texts(samples)

#Recover the word index that was computed above
word_index = tk.word_index
print('Found %s unique tokens.' % len(word_index))
print(word_index)

Found 35 unique tokens.
{'OOV': 1, 'i': 2, 'year': 3, 'the': 4, 'my': 5, 'will': 6, 'next': 7, 'cat': 8, 'sat': 9, 'on': 10, 'mat': 11, 'dog': 12, 'ate': 13, 'homework': 14, 'friend': 15, 'name': 16, 'is': 17, 'tony': 18, 'singh': 19, 'had': 20, 'visited': 21, 'dubai': 22, 'last': 23, 'visit': 24, 'singapore': 25, 'am': 26, 'a': 27, 'software': 28, 'engineer': 29, 'got': 30, 'good': 31, 'appraisal': 32, 'this': 33, 'change': 34, 'job': 35}


In [ ]:
#Turns strings into lists of integer indices
sequences = tk.texts_to_sequences(samples)
print(sequences)

[[4, 8, 9, 10, 4, 11], [4, 12, 13, 5, 14], [5, 15, 16, 17, 18, 19], [2, 20, 21, 22, 23, 3], [2, 6, 24, 25, 7, 3], [2, 26, 27, 28, 29], [2, 30, 31, 32, 33, 3], [2, 6, 34, 35, 7, 3]]


In [ ]:
#Padding
data = pad_sequences(sequences, maxlen=10, padding='post')
print(data)

[[ 4  8  9 10  4 11  0  0  0  0]
 [ 4 12 13  5 14  0  0  0  0  0]
 [ 5 15 16 17 18 19  0  0  0  0]
 [ 2 20 21 22 23  3  0  0  0  0]
 [ 2  6 24 25  7  3  0  0  0  0]
 [ 2 26 27 28 29  0  0  0  0  0]
 [ 2 30 31 32 33  3  0  0  0  0]
 [ 2  6 34 35  7  3  0  0  0  0]]


In [ ]:
#Predicting output
embedding_model.compile(optimizer='rmsprop', loss='mean_absolute_error', metrics=['mean_absolute_error'])
output_array = embedding_model.predict(data)
print(output_array)
print(output_array.shape)

[[[-0.00136527  0.01924985  0.00992731  0.01133356  0.03673916]
  [ 0.03897518 -0.02412759 -0.00244956  0.03174832 -0.04638056]
  [-0.03650631 -0.01699485 -0.048102   -0.0006643   0.03507913]
  [-0.0149225   0.03340178  0.02536513  0.00022537  0.04577419]
  [-0.00136527  0.01924985  0.00992731  0.01133356  0.03673916]
  [ 0.00237679 -0.02707014 -0.03864337 -0.00760462 -0.02959684]
  [-0.03677334  0.02138168  0.03116913 -0.01848551  0.03126273]
  [-0.03677334  0.02138168  0.03116913 -0.01848551  0.03126273]
  [-0.03677334  0.02138168  0.03116913 -0.01848551  0.03126273]
  [-0.03677334  0.02138168  0.03116913 -0.01848551  0.03126273]]

 [[-0.00136527  0.01924985  0.00992731  0.01133356  0.03673916]
  [-0.03597109  0.00266447 -0.03730625  0.0472289  -0.03918529]
  [ 0.00620624 -0.00549798 -0.03116912  0.01388284 -0.02093198]
  [-0.04255113 -0.02191206  0.01379234  0.00139534  0.03323114]
  [-0.01890378 -0.01950195 -0.01867659 -0.01917452  0.02959986]
  [-0.03677334  0.02138168  0.03116913