In [1]:
from platform import python_version
print(python_version())

3.6.9


In [2]:
import tensorflow as tf
print(f'Tensorflow version currently used is {tf.__version__}')
#tf.test.gpu_device_name()
#!cat /proc/cpuinfo

Tensorflow version currently used is 2.4.0


In [3]:
import keras
print(f'Keras version currently used is {keras.__version__}')

Keras version currently used is 2.4.3


In [ ]:
#from tensorflow.python.client import device_lib
#device_lib.list_local_devices()

In [16]:
import numpy as np
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
print(train_images.shape)
print(train_images.ndim)
print(len(train_labels))
print(train_labels)

print(test_images.shape)
print(len(test_labels))
print(test_labels)

(60000, 28, 28)
3
60000
[5 0 4 ... 5 6 8]
(10000, 28, 28)
10000
[7 2 1 ... 4 5 6]


In [17]:
from keras import models, Sequential
from keras import layers
network = models.Sequential()
network.add(layers.Conv2D(32,(3,3), padding="valid", strides=(1, 1), kernel_initializer="glorot_uniform", activation='relu', input_shape=(28,28,1)))
network.add(layers.MaxPool2D(2,2))
network.add(layers.Conv2D(64,(3,3), padding="valid", activation='relu'))
network.add(layers.MaxPool2D(2,2))
network.add(layers.Conv2D(64,(3,3), padding="valid", activation='relu'))
network.add(layers.Flatten())
network.add(layers.Dense(64, activation='relu'))
network.add(layers.Dense(10, activation='softmax'))
print(network.summary())

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_19 (Conv2D)           (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_12 (MaxPooling (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_20 (Conv2D)           (None, 11, 11, 64)        18496     
_________________________________________________________________
max_pooling2d_13 (MaxPooling (None, 5, 5, 64)          0         
_________________________________________________________________
conv2d_21 (Conv2D)           (None, 3, 3, 64)          36928     
_________________________________________________________________
flatten_5 (Flatten)          (None, 576)               0         
_________________________________________________________________
dense_10 (Dense)             (None, 64)               

In [18]:
network.compile(optimizer='rmsprop', loss = 'categorical_crossentropy', metrics=['accuracy'])

In [19]:
train_images = train_images.reshape((60000, 28, 28, 1))
train_images = train_images.astype('float32')/255
print(train_images.shape)
print(train_images.ndim)

test_images = test_images.reshape((10000, 28, 28, 1))
test_images = test_images.astype('float32')/255

from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

(60000, 28, 28, 1)
4


In [20]:
network.fit(train_images, train_labels, epochs=5, batch_size=64)

Epoch 1/5
938/938 [==============================] - 11s 4ms/step - loss: 0.3805 - accuracy: 0.8770
Epoch 2/5
938/938 [==============================] - 3s 4ms/step - loss: 0.0479 - accuracy: 0.9853
Epoch 3/5
938/938 [==============================] - 3s 4ms/step - loss: 0.0322 - accuracy: 0.9899
Epoch 4/5
938/938 [==============================] - 3s 4ms/step - loss: 0.0241 - accuracy: 0.9929
Epoch 5/5
938/938 [==============================] - 3s 4ms/step - loss: 0.0175 - accuracy: 0.9947


In [21]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.0290 - accuracy: 0.9904
test_acc: 0.9904000163078308


In [22]:
# save model and architecture to single file
network.save('mnist_cnn1.h5')

In [23]:
# serialize model to JSON
json_config = network.to_json()
with open('mnist_cnn1_model.json', 'w') as json_file:
    json_file.write(json_config)

In [ ]:
predictions = (models.load_model("mnist_cnn1.h5")).predict(test_images)
print(predictions)

[[3.16313697e-10 4.30824560e-12 1.77618258e-08 ... 1.00000000e+00
  2.37046327e-10 1.60540043e-08]
 [1.14390424e-07 6.43455422e-08 9.99999881e-01 ... 1.16761147e-12
  4.65089800e-10 1.58141356e-14]
 [1.72879986e-08 9.99992013e-01 4.20220410e-08 ... 1.30431590e-06
  8.67254130e-07 7.45770734e-08]
 ...
 [2.73186448e-18 4.76135884e-12 3.56052332e-14 ... 1.35659192e-11
  8.08321410e-09 1.12358112e-09]
 [2.18483702e-08 1.88351328e-14 2.11071785e-11 ... 3.95664317e-12
  1.67883831e-04 2.98873676e-10]
 [4.05113013e-07 1.15963246e-11 4.89679337e-07 ... 1.98905684e-13
  3.38593259e-06 4.20558597e-12]]


In [ ]:
print(np.argmax(predictions[20]))

9


In [ ]:
print(test_labels[20])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [24]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [25]:
!ls /content/drive/MyDrive/*.jpg
img = load_img('/content/drive/My Drive/img_5.jpg', color_mode = "grayscale", target_size=(28, 28))

/content/drive/MyDrive/img_5.jpg  /content/drive/MyDrive/img_6.jpg


In [26]:
# convert to array
img = img_to_array(img, data_format="channels_last", dtype="float32")
print(img.shape)
img = img / 255.0
img = img.reshape(1,28 , 28, 1)
print(img.shape)

(28, 28, 1)
(1, 28, 28, 1)


In [27]:
print((models.load_model("mnist_cnn1.h5")).predict_classes(img))

[5]


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '
